name: dragonballgo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.0.3
  location: ^3.0.2

  cupertino_icons: ^1.0.0
  flutter_translate: ^1.6.0
  shared_preferences: ^0.5.12+4
  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  rflutter_alert: ^1.1.0
  http: ^0.12.2
  fluro: ^2.0.3
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - locale/i18n/
    - assets/images/
  fonts:
    - family: Rozanova
      fonts:
        - asset: assets/fonts/rozanova/rozanova-semibold.otf
          weight: 400

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
